/**
 * Scrabble dictionary instances.
 *
 * Words are loaded from pre-compiled length-grouped files generated by
 * `scripts/build-dicts.mjs`. Each dictionary is reconstituted as:
 *
 *   common ∪ delta
 *
 * where "common" contains words shared by all three dictionaries.
 */

import { BiDirectionalDictionary } from './dict';
import { COMMON_WORDS } from './compiled/common';
import { SOWPODS_DELTA_WORDS } from './compiled/sowpods-delta';
import { TWL06_DELTA_WORDS } from './compiled/twl06-delta';
import { CSW22_DELTA_WORDS } from './compiled/csw22-delta';

// ============================================================
// Dictionary instances — reconstituted from common + delta
// ============================================================

export const SowpodsDictionary = new BiDirectionalDictionary()
    .loadCompiled(COMMON_WORDS)
    .loadCompiled(SOWPODS_DELTA_WORDS);

export const Twl06Dictionary = new BiDirectionalDictionary()
    .loadCompiled(COMMON_WORDS)
    .loadCompiled(TWL06_DELTA_WORDS);

export const Csw22Dictionary = new BiDirectionalDictionary()
    .loadCompiled(COMMON_WORDS)
    .loadCompiled(CSW22_DELTA_WORDS);

/**
 * Dictionary metadata for the selector UI
 */
export interface DictionaryInfo {
    id: 'sowpods' | 'twl06' | 'csw22';
    name: string;
    description: string;
    instance: BiDirectionalDictionary;
}

export const AVAILABLE_DICTIONARIES: DictionaryInfo[] = [
    {
        id: 'sowpods',
        name: 'SOWPODS',
        description: 'Int\'l tournament standard (OSW + TWL)',
        instance: SowpodsDictionary,
    },
    {
        id: 'twl06',
        name: 'TWL06',
        description: 'North American tournament list',
        instance: Twl06Dictionary,
    },
    {
        id: 'csw22',
        name: 'CSW22',
        description: '2022 Collins Scrabble Words (latest)',
        instance: Csw22Dictionary,
    },
];

export { BiDirectionalDictionary } from './dict';
