/**
 * build-dicts.mjs — Pre-compile Scrabble dictionaries into length-grouped,
 * pipe-delimited files with optimal deduplication.
 *
 * This script:
 *   1. Parses raw word arrays from src/dict/{sowpods,twl06,CSW22}.ts
 *   2. Computes all 7 Venn-diagram "atoms" (regions of set overlap)
 *   3. Enumerates all valid ways to group atoms into chunk files
 *   4. Gzip-measures each candidate and picks the smallest
 *   5. Writes the winning chunk files + a manifest.ts
 *
 * Atoms (Venn regions for 3 dictionaries A=SOWPODS, B=CSW22, C=TWL06):
 *   ABC = A ∩ B ∩ C        AB = (A∩B) \ C       AC = (A∩C) \ B
 *   BC  = (B∩C) \ A        A  = A \ (B∪C)       B  = B \ (A∪C)
 *   C   = C \ (A∪B)
 *
 * Usage:  node scripts/build-dicts.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { gzipSync } from 'zlib';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DICT_SRC = join(ROOT, 'src', 'dict');
const COMPILED_DIR = join(DICT_SRC, 'compiled');

// ── Parse a TS file that exports a const string array ────────────────
function parseWordList(filename) {
    const raw = readFileSync(join(DICT_SRC, filename), 'utf-8');
    const start = raw.indexOf('[');
    const end = raw.lastIndexOf(']');
    if (start === -1 || end === -1) {
        throw new Error(`Could not find array in ${filename}`);
    }
    const arraySrc = raw.slice(start, end + 1);
    const cleaned = arraySrc
        .replace(/,\s*\]/g, ']')
        .replace(/,\s*\n\s*\]/g, '\n]');
    const words = JSON.parse(cleaned);
    if (!Array.isArray(words)) {
        throw new Error(`Expected array in ${filename}, got ${typeof words}`);
    }
    return new Set(words.map(w => w.toLowerCase()));
}

// ── Group a Set of words by length, sort, join ───────────────────────
function groupByLength(wordSet) {
    const groups = {};
    for (const word of wordSet) {
        const len = word.length;
        if (!groups[len]) groups[len] = [];
        groups[len].push(word);
    }
    const result = {};
    for (const len of Object.keys(groups).sort((a, b) => +a - +b)) {
        groups[len].sort();
        result[len] = groups[len].join('|');
    }
    return result;
}

// ── Serialize grouped data to the TS export format ───────────────────
function serializeChunk(name, groups) {
    const entries = Object.entries(groups)
        .map(([len, words]) => `  ${len}: ${JSON.stringify(words)}`)
        .join(',\n');
    return [
        `// Auto-generated by scripts/build-dicts.mjs — DO NOT EDIT`,
        `export const ${name}: Record<number, string> = {`,
        entries,
        `};`,
        '',
    ].join('\n');
}

// ── Generate all set partitions of an array of items ─────────────────
// Returns an array of partitions, where each partition is an array of blocks.
function* setPartitions(items) {
    if (items.length === 0) {
        yield [];
        return;
    }
    const [first, ...rest] = items;
    for (const partition of setPartitions(rest)) {
        // Option 1: first in its own block
        yield [[first], ...partition];
        // Option 2: first joins each existing block
        for (let i = 0; i < partition.length; i++) {
            const copy = partition.map(b => [...b]);
            copy[i].push(first);
            yield copy;
        }
    }
}

// ── Set union ────────────────────────────────────────────────────────
function union(...sets) {
    const result = new Set();
    for (const s of sets) for (const x of s) result.add(x);
    return result;
}

// =====================================================================
// MAIN
// =====================================================================
console.log('Building compiled dictionaries...\n');

// 1. Parse source files
const A = parseWordList('sowpods.ts');  // SOWPODS
const B = parseWordList('CSW22.ts');    // CSW22
const C = parseWordList('twl06.ts');    // TWL06

console.log(`  SOWPODS: ${A.size.toLocaleString()} words`);
console.log(`  CSW22:   ${B.size.toLocaleString()} words`);
console.log(`  TWL06:   ${C.size.toLocaleString()} words`);

// 2. Compute all 7 Venn atoms
const atoms = {
    ABC: new Set([...A].filter(w => B.has(w) && C.has(w))),
    AB: new Set([...A].filter(w => B.has(w) && !C.has(w))),
    AC: new Set([...A].filter(w => !B.has(w) && C.has(w))),
    BC: new Set([...B].filter(w => !A.has(w) && C.has(w))),
    A_: new Set([...A].filter(w => !B.has(w) && !C.has(w))),
    B_: new Set([...B].filter(w => !A.has(w) && !C.has(w))),
    C_: new Set([...C].filter(w => !A.has(w) && !B.has(w))),
};

// Dict → which atoms it needs
const dictAtoms = {
    sowpods: ['ABC', 'AB', 'AC', 'A_'],
    csw22: ['ABC', 'AB', 'BC', 'B_'],
    twl06: ['ABC', 'AC', 'BC', 'C_'],
};

// Print atom sizes, skip empties
const activeAtoms = [];
console.log('\n  Venn atoms:');
for (const [name, set] of Object.entries(atoms)) {
    if (set.size > 0) {
        console.log(`    ${name}: ${set.size.toLocaleString()} words`);
        activeAtoms.push(name);
    }
}

// Verify atoms reconstruct correctly
for (const [dict, needed] of Object.entries(dictAtoms)) {
    const recon = union(...needed.map(n => atoms[n]));
    const orig = { sowpods: A, csw22: B, twl06: C }[dict];
    if (recon.size !== orig.size) {
        console.error(`  ✗ ${dict} reconstitution FAILED: ${recon.size} vs ${orig.size}`);
        process.exit(1);
    }
}
console.log('  ✓ All dictionaries reconstitute correctly from atoms');

// 3. Pre-group each atom by length
const atomGrouped = {};
for (const name of activeAtoms) {
    atomGrouped[name] = groupByLength(atoms[name]);
}

// 4. Enumerate partitions and gzip-measure
console.log('\n  Exploring partition strategies...');

let bestPartition = null;
let bestSize = Infinity;
let candidatesChecked = 0;

for (const partition of setPartitions(activeAtoms)) {
    candidatesChecked++;

    // Check validity: each dictionary must be expressible as a union of some blocks
    let valid = true;
    const dictBlocks = {}; // dict → array of block indices
    for (const [dict, needed] of Object.entries(dictAtoms)) {
        const neededSet = new Set(needed.filter(n => atoms[n].size > 0));
        // Each block in the partition covers some atoms. Find blocks that cover needed atoms.
        const blocks = [];
        const covered = new Set();
        for (let bi = 0; bi < partition.length; bi++) {
            const blockSet = new Set(partition[bi]);
            // Does this block contain ONLY atoms we need?
            let allNeeded = true;
            for (const a of blockSet) {
                if (!neededSet.has(a)) { allNeeded = false; break; }
            }
            if (allNeeded) {
                blocks.push(bi);
                for (const a of blockSet) covered.add(a);
            }
        }
        // All needed atoms must be covered
        for (const n of neededSet) {
            if (!covered.has(n)) { valid = false; break; }
        }
        if (!valid) break;
        dictBlocks[dict] = blocks;
    }

    if (!valid) continue;

    // Measure gzip size of this partition
    let totalGzip = 0;
    for (let bi = 0; bi < partition.length; bi++) {
        // Merge grouped data from all atoms in this block
        const merged = {};
        for (const atomName of partition[bi]) {
            const g = atomGrouped[atomName];
            for (const [len, words] of Object.entries(g)) {
                if (!merged[len]) merged[len] = [];
                merged[len].push(words);
            }
        }
        // Sort and re-join (atoms were individually sorted, but merging unsorts)
        const final = {};
        for (const len of Object.keys(merged).sort((a, b) => +a - +b)) {
            const allWords = merged[len].flatMap(s => s.split('|'));
            allWords.sort();
            final[len] = allWords.join('|');
        }
        const serialized = serializeChunk(`CHUNK_${bi}`, final);
        totalGzip += gzipSync(serialized).length;
    }

    if (totalGzip < bestSize) {
        bestSize = totalGzip;
        bestPartition = { partition, dictBlocks, totalGzip };
    }
}

console.log(`  Checked ${candidatesChecked} partitions, ${bestPartition ? 'found optimal' : 'NONE FOUND'}`);
console.log(`  Best gzip size: ${(bestSize / 1024).toFixed(1)} KB, ${bestPartition.partition.length} chunks`);

// 5. Write the winning chunk files + manifest
mkdirSync(COMPILED_DIR, { recursive: true });
console.log('');

const chunkNames = [];
for (let bi = 0; bi < bestPartition.partition.length; bi++) {
    const chunkName = `chunk-${bi}`;
    chunkNames.push(chunkName);

    const merged = {};
    for (const atomName of bestPartition.partition[bi]) {
        const g = atomGrouped[atomName];
        for (const [len, words] of Object.entries(g)) {
            if (!merged[len]) merged[len] = [];
            merged[len].push(words);
        }
    }
    const final = {};
    for (const len of Object.keys(merged).sort((a, b) => +a - +b)) {
        const allWords = merged[len].flatMap(s => s.split('|'));
        allWords.sort();
        final[len] = allWords.join('|');
    }

    const exportName = `CHUNK_${bi}_WORDS`;
    const content = serializeChunk(exportName, final);
    const path = join(COMPILED_DIR, `${chunkName}.ts`);
    writeFileSync(path, content, 'utf-8');
    console.log(`  ✓ ${chunkName}.ts  (${bestPartition.partition[bi].join(' + ')} → ${content.length.toLocaleString()} B raw, ${(gzipSync(content).length / 1024).toFixed(1)} KB gzip)`);
}

// 6. Write manifest.ts — tells scrabbledicts.ts how to reconstitute
const manifestLines = [
    `// Auto-generated by scripts/build-dicts.mjs — DO NOT EDIT`,
    `// Optimal partition: ${bestPartition.partition.length} chunks, ${(bestSize / 1024).toFixed(1)} KB gzip`,
    `// Atoms per chunk: ${bestPartition.partition.map((b, i) => `[${i}]: ${b.join('+')}`).join(', ')}`,
    '',
    `import { BiDirectionalDictionary } from '../dict';`,
];
for (let bi = 0; bi < bestPartition.partition.length; bi++) {
    manifestLines.push(`import { CHUNK_${bi}_WORDS } from './chunk-${bi}';`);
}
manifestLines.push('');

for (const [dict, blocks] of Object.entries(bestPartition.dictBlocks)) {
    const dictVar = { sowpods: 'SowpodsDictionary', csw22: 'Csw22Dictionary', twl06: 'Twl06Dictionary' }[dict];
    const loads = blocks.map(bi => `CHUNK_${bi}_WORDS`).join(', ');
    manifestLines.push(`export const ${dictVar} = new BiDirectionalDictionary()`);
    for (const bi of blocks) {
        manifestLines.push(`    .loadCompiled(CHUNK_${bi}_WORDS)`);
    }
    manifestLines.push(`;`);
    manifestLines.push('');
}

const manifestPath = join(COMPILED_DIR, 'manifest.ts');
writeFileSync(manifestPath, manifestLines.join('\n'), 'utf-8');
console.log(`\n  ✓ manifest.ts written`);
console.log(`  SOWPODS ← chunks [${bestPartition.dictBlocks.sowpods}]`);
console.log(`  CSW22   ← chunks [${bestPartition.dictBlocks.csw22}]`);
console.log(`  TWL06   ← chunks [${bestPartition.dictBlocks.twl06}]`);
console.log('  Done.\n');
