/**
 * build-dicts.mjs — Pre-compile Scrabble dictionaries into length-grouped,
 * pipe-delimited files with common-word deduplication.
 *
 * Strategy:
 *   1. Parse raw word arrays from src/dict/{sowpods,twl06,CSW22}.ts
 *   2. Compute: COMMON = intersection of all three
 *   3. Compute: SOWPODS_CSW22_SHARED = (SOWPODS ∩ CSW22) \ COMMON
 *   4. Compute: SOWPODS_UNIQUE = SOWPODS \ (COMMON ∪ CSW22)
 *   5. Compute: CSW22_UNIQUE  = CSW22 \ (COMMON ∪ SOWPODS)
 *   6. Compute: TWL06_DELTA   = TWL06 \ COMMON
 *   7. Group each set by word length, sort, join with "|"
 *   8. Write 5 compiled TS files as Record<number, string>
 *
 * Runtime reconstitution:
 *   SOWPODS = COMMON ∪ SOWPODS_CSW22_SHARED ∪ SOWPODS_UNIQUE
 *   CSW22   = COMMON ∪ SOWPODS_CSW22_SHARED ∪ CSW22_UNIQUE
 *   TWL06   = COMMON ∪ TWL06_DELTA
 *
 * Output:
 *   src/dict/compiled/common.ts               — words in all 3 dicts
 *   src/dict/compiled/sowpods-csw22-shared.ts  — in both SOWPODS & CSW22, not TWL06
 *   src/dict/compiled/sowpods-unique.ts        — SOWPODS-only words
 *   src/dict/compiled/csw22-unique.ts          — CSW22-only words
 *   src/dict/compiled/twl06-delta.ts           — TWL06-only words
 *
 * Usage:  node scripts/build-dicts.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DICT_SRC = join(ROOT, 'src', 'dict');
const COMPILED_DIR = join(DICT_SRC, 'compiled');

// ── Parse a TS file that exports a const string array ────────────────
function parseWordList(filename) {
    const raw = readFileSync(join(DICT_SRC, filename), 'utf-8');

    // Find the array literal between [ and ]
    const start = raw.indexOf('[');
    const end = raw.lastIndexOf(']');
    if (start === -1 || end === -1) {
        throw new Error(`Could not find array in ${filename}`);
    }

    const arraySrc = raw.slice(start, end + 1);

    // Normalize to valid JSON: strip trailing commas before ] or before newline+]
    const cleaned = arraySrc
        .replace(/,\s*\]/g, ']')          // trailing comma before ]
        .replace(/,\s*\n\s*\]/g, '\n]');  // trailing comma on its own line

    const words = JSON.parse(cleaned);

    if (!Array.isArray(words)) {
        throw new Error(`Expected array in ${filename}, got ${typeof words}`);
    }

    return new Set(words.map(w => w.toLowerCase()));
}

// ── Group a Set of words by length, sort, join ───────────────────────
function groupByLength(wordSet) {
    const groups = {};
    for (const word of wordSet) {
        const len = word.length;
        if (!groups[len]) groups[len] = [];
        groups[len].push(word);
    }
    // Sort each group and join with pipe
    const result = {};
    for (const len of Object.keys(groups).sort((a, b) => +a - +b)) {
        groups[len].sort();
        result[len] = groups[len].join('|');
    }
    return result;
}

// ── Write a compiled TS file ─────────────────────────────────────────
function writeCompiled(name, groups) {
    const path = join(COMPILED_DIR, `${name}.ts`);

    // Build a compact TS export: Record<number, string>
    const entries = Object.entries(groups)
        .map(([len, words]) => `  ${len}: ${JSON.stringify(words)}`)
        .join(',\n');

    const content = [
        `// Auto-generated by scripts/build-dicts.mjs — DO NOT EDIT`,
        `// ${name} dictionary — length → pipe-delimited sorted words`,
        `export const ${name.toUpperCase().replace(/-/g, '_')}_WORDS: Record<number, string> = {`,
        entries,
        `};`,
        '',
    ].join('\n');

    writeFileSync(path, content, 'utf-8');
    console.log(`  ✓ wrote ${path} (${content.length.toLocaleString()} bytes)`);
}

// ── Main ─────────────────────────────────────────────────────────────
console.log('Building compiled dictionaries...\n');

// 1. Parse source files
const sowpods = parseWordList('sowpods.ts');
const twl06 = parseWordList('twl06.ts');
const csw22 = parseWordList('CSW22.ts');

console.log(`  SOWPODS: ${sowpods.size.toLocaleString()} words`);
console.log(`  TWL06:   ${twl06.size.toLocaleString()} words`);
console.log(`  CSW22:   ${csw22.size.toLocaleString()} words`);

// 2. Compute intersection (common to all three)
const common = new Set([...sowpods].filter(w => twl06.has(w) && csw22.has(w)));
console.log(`\n  Common (all 3):  ${common.size.toLocaleString()} words`);

// 3. Compute SOWPODS-CSW22 shared set (words in both but NOT in TWL06)
const sowpodsCsw22Shared = new Set(
    [...sowpods].filter(w => !common.has(w) && csw22.has(w))
);
console.log(`  SOWPODS∩CSW22 (not TWL): ${sowpodsCsw22Shared.size.toLocaleString()} words`);

// 4. Compute truly-unique deltas
const sowpodsUnique = new Set(
    [...sowpods].filter(w => !common.has(w) && !csw22.has(w))
);
const csw22Unique = new Set(
    [...csw22].filter(w => !common.has(w) && !sowpods.has(w))
);
const twl06Delta = new Set([...twl06].filter(w => !common.has(w)));

console.log(`  SOWPODS truly unique: ${sowpodsUnique.size.toLocaleString()} words`);
console.log(`  CSW22 truly unique:   ${csw22Unique.size.toLocaleString()} words`);
console.log(`  TWL06-only:            ${twl06Delta.size.toLocaleString()} words`);

// Verify reconstitution
const sowpodsRecon = new Set([...common, ...sowpodsCsw22Shared, ...sowpodsUnique]);
const csw22Recon = new Set([...common, ...sowpodsCsw22Shared, ...csw22Unique]);
const twl06Recon = new Set([...common, ...twl06Delta]);

console.log(`\n  Reconstitution check:`);
console.log(`    SOWPODS: ${sowpodsRecon.size === sowpods.size ? '✓' : '✗ FAILED'} (${sowpodsRecon.size} vs ${sowpods.size})`);
console.log(`    CSW22:   ${csw22Recon.size === csw22.size ? '✓' : '✗ FAILED'} (${csw22Recon.size} vs ${csw22.size})`);
console.log(`    TWL06:   ${twl06Recon.size === twl06.size ? '✓' : '✗ FAILED'} (${twl06Recon.size} vs ${twl06.size})`);

// 5. Group by length
const commonGrouped = groupByLength(common);
const sowpodsCsw22Grouped = groupByLength(sowpodsCsw22Shared);
const sowpodsUniqueGrouped = groupByLength(sowpodsUnique);
const csw22UniqueGrouped = groupByLength(csw22Unique);
const twl06Grouped = groupByLength(twl06Delta);

// 6. Write compiled files
mkdirSync(COMPILED_DIR, { recursive: true });
console.log('');
writeCompiled('common', commonGrouped);
writeCompiled('sowpods-csw22-shared', sowpodsCsw22Grouped);
writeCompiled('sowpods-unique', sowpodsUniqueGrouped);
writeCompiled('csw22-unique', csw22UniqueGrouped);
writeCompiled('twl06-delta', twl06Grouped);

// 7. Summary
const totalWords = common.size + sowpodsCsw22Shared.size + sowpodsUnique.size + csw22Unique.size + twl06Delta.size;
console.log(`\n  Total unique word instances across all 5 files: ${totalWords.toLocaleString()}`);
console.log('  Done.\n');
