/**
 * build-dicts.mjs — Pre-compile Scrabble dictionaries into length-grouped,
 * pipe-delimited files with optimal deduplication.
 *
 * This script:
 *   1. Parses raw word arrays from src/dict/{sowpods,twl06,CSW22}.ts
 *      + src/dict/FINAL-WOW24-Full-Alphabetical.txt
 *   2. Computes all 15 Venn-diagram "atoms" (regions of 4-set overlap)
 *   3. Assigns each non-empty atom its own chunk file (1:1 mapping)
 *   4. Writes chunk files + a manifest.ts
 *
 * Atoms (Venn regions for 4 sets: A=SOWPODS, B=CSW22, C=TWL06, D=WOW24):
 *   ABCD  ABD  ACD  BCD  ABC  AB  AC  AD  BC  BD  CD  A  B  C  D
 *
 * With 4 sets, exhaustive partition enumeration is infeasible
 * (B(15) ≈ 1.4B), so we use one-chunk-per-atom.
 *
 * Usage:  node scripts/build-dicts.mjs
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { gzipSync } from 'zlib';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DICT_SRC = join(ROOT, 'src', 'dict');
const COMPILED_DIR = join(DICT_SRC, 'compiled');

// ── Parse a TS file that exports a const string array ────────────────
function parseWordList(filename) {
    const raw = readFileSync(join(DICT_SRC, filename), 'utf-8');
    const start = raw.indexOf('[');
    const end = raw.lastIndexOf(']');
    if (start === -1 || end === -1) {
        throw new Error(`Could not find array in ${filename}`);
    }
    const arraySrc = raw.slice(start, end + 1);
    const cleaned = arraySrc
        .replace(/,\s*\]/g, ']')
        .replace(/,\s*\n\s*\]/g, '\n]');
    const words = JSON.parse(cleaned);
    if (!Array.isArray(words)) {
        throw new Error(`Expected array in ${filename}, got ${typeof words}`);
    }
    return new Set(words.map(w => w.toLowerCase()));
}

// ── Parse a plain-text word list (uppercase, one word per line) ──────
function parseTextWordList(filename) {
    const raw = readFileSync(join(DICT_SRC, filename), 'utf-8');
    return new Set(
        raw.split(/\r?\n/)
            .map(w => w.trim().toLowerCase())
            .filter(w => w.length > 0)
    );
}

// ── Group a Set of words by length, sort, join ───────────────────────
function groupByLength(wordSet) {
    const groups = {};
    for (const word of wordSet) {
        const len = word.length;
        if (!groups[len]) groups[len] = [];
        groups[len].push(word);
    }
    const result = {};
    for (const len of Object.keys(groups).sort((a, b) => +a - +b)) {
        groups[len].sort();
        result[len] = groups[len].join('|');
    }
    return result;
}

// ── Serialize grouped data to the TS export format ───────────────────
function serializeChunk(name, groups) {
    const entries = Object.entries(groups)
        .map(([len, words]) => `  ${len}: ${JSON.stringify(words)}`)
        .join(',\n');
    return [
        `// Auto-generated by scripts/build-dicts.mjs — DO NOT EDIT`,
        `export const ${name}: Record<number, string> = {`,
        entries,
        `};`,
        '',
    ].join('\n');
}

// ── Set union ────────────────────────────────────────────────────────
function union(...sets) {
    const result = new Set();
    for (const s of sets) for (const x of s) result.add(x);
    return result;
}

// =====================================================================
// MAIN
// =====================================================================
console.log('Building compiled dictionaries...\n');

// 1. Parse source files
const A = parseWordList('sowpods.ts');  // SOWPODS
const B = parseWordList('CSW22.ts');    // CSW22
const C = parseWordList('twl06.ts');    // TWL06
const D = parseTextWordList('FINAL-WOW24-Full-Alphabetical.txt'); // WOW24

console.log(`  SOWPODS: ${A.size.toLocaleString()} words`);
console.log(`  CSW22:   ${B.size.toLocaleString()} words`);
console.log(`  TWL06:   ${C.size.toLocaleString()} words`);
console.log(`  WOW24:   ${D.size.toLocaleString()} words`);

// 2. Compute all 15 Venn atoms (non-empty subsets of {A,B,C,D})
// We use binary mask: bit0=A, bit1=B, bit2=C, bit3=D
// Atom name is the concatenation of letters whose bits are set.
function computeAtom(mask, sets) {
    let result = null;
    for (let i = 0; i < 4; i++) {
        const set = sets[i];
        if (mask & (1 << i)) {
            // This set must CONTAIN the word
            result = result === null ? new Set(set) : new Set([...result].filter(w => set.has(w)));
        } else {
            // This set must NOT contain the word
            if (result === null) {
                // Start with the universal set (union of all)
                result = union(...sets);
            }
            result = new Set([...result].filter(w => !set.has(w)));
        }
    }
    return result || new Set();
}

const allSets = [A, B, C, D];
const atoms = {};
const ATOM_NAMES = [];
for (let mask = 1; mask < 16; mask++) {
    const name = ['A', 'B', 'C', 'D'].filter((_, i) => mask & (1 << i)).join('');
    ATOM_NAMES.push(name);
    atoms[name] = computeAtom(mask, allSets);
}

// Dict → which atoms it needs (atoms whose name contains the dict's letter)
const dictAtomMap = {
    sowpods: ATOM_NAMES.filter(n => n.includes('A')),
    csw22: ATOM_NAMES.filter(n => n.includes('B')),
    twl06: ATOM_NAMES.filter(n => n.includes('C')),
    wow24: ATOM_NAMES.filter(n => n.includes('D')),
};

// Print atom sizes, collect non-empty ones
const activeAtoms = [];
console.log('\n  Venn atoms:');
for (const name of ATOM_NAMES) {
    const size = atoms[name].size;
    if (size > 0) {
        console.log(`    ${name}: ${size.toLocaleString()} words`);
        activeAtoms.push(name);
    }
}

// Verify atoms reconstruct correctly
for (const [dict, needed] of Object.entries(dictAtomMap)) {
    const recon = union(...needed.map(n => atoms[n]));
    const orig = { sowpods: A, csw22: B, twl06: C, wow24: D }[dict];
    if (recon.size !== orig.size) {
        console.error(`  ✗ ${dict} reconstitution FAILED: ${recon.size} vs ${orig.size}`);
        process.exit(1);
    }
}
console.log('  ✓ All dictionaries reconstitute correctly from atoms');

// 3. Write one chunk per non-empty atom
mkdirSync(COMPILED_DIR, { recursive: true });
console.log('');

const chunkMapping = {}; // atomName → chunkIndex
let chunkIndex = 0;

for (const name of activeAtoms) {
    chunkMapping[name] = chunkIndex;
    const groups = groupByLength(atoms[name]);
    const exportName = `CHUNK_${chunkIndex}_WORDS`;
    const content = serializeChunk(exportName, groups);
    const chunkFile = `chunk-${chunkIndex}.ts`;
    const path = join(COMPILED_DIR, chunkFile);
    writeFileSync(path, content, 'utf-8');
    const gzipSize = gzipSync(content).length;
    console.log(`  ✓ ${chunkFile}  (atom ${name}: ${atoms[name].size.toLocaleString()} words → ${content.length.toLocaleString()} B raw, ${(gzipSize / 1024).toFixed(1)} KB gzip)`);
    chunkIndex++;
}

// 4. Write manifest.ts
const dictToChunks = {};
for (const [dict, neededAtoms] of Object.entries(dictAtomMap)) {
    dictToChunks[dict] = neededAtoms
        .filter(n => atoms[n].size > 0)
        .map(n => chunkMapping[n])
        .sort((a, b) => a - b);
}

const dictVarNames = { sowpods: 'SowpodsDictionary', csw22: 'Csw22Dictionary', twl06: 'Twl06Dictionary', wow24: 'Wow24Dictionary' };

const manifestLines = [
    `// Auto-generated by scripts/build-dicts.mjs — DO NOT EDIT`,
    `// Strategy: one-chunk-per-atom — ${chunkIndex} non-empty atoms, ${chunkIndex} chunks`,
    `// Atom→chunk: ${activeAtoms.map(a => `${a}→${chunkMapping[a]}`).join(', ')}`,
    '',
    `import { BiDirectionalDictionary } from '../dict';`,
];
for (let i = 0; i < chunkIndex; i++) {
    manifestLines.push(`import { CHUNK_${i}_WORDS } from './chunk-${i}';`);
}
manifestLines.push('');

// DICT_MAP comments for validators
for (const [dict, chunks] of Object.entries(dictToChunks)) {
    manifestLines.push(`// DICT_MAP: ${dictVarNames[dict]} ← chunks [${chunks.join(',')}]`);
}
manifestLines.push('');

for (const [dict, chunks] of Object.entries(dictToChunks)) {
    const varName = dictVarNames[dict];
    manifestLines.push(`export const ${varName} = new BiDirectionalDictionary()`);
    for (const i of chunks) {
        manifestLines.push(`    .loadCompiled(CHUNK_${i}_WORDS)`);
    }
    manifestLines.push(`;`);
    manifestLines.push('');
}

const manifestPath = join(COMPILED_DIR, 'manifest.ts');
writeFileSync(manifestPath, manifestLines.join('\n'), 'utf-8');
console.log(`\n  ✓ manifest.ts written`);
for (const [dict, chunks] of Object.entries(dictToChunks)) {
    console.log(`  ${dict.toUpperCase()} ← chunks [${chunks.join(',')}]`);
}
console.log('  Done.\n');
